/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import domain.*;
import domain.operations.Operations;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 * Edit levels view of the application. The user select an existing level to edit it or 
 * create a new one.
 * @author Pol Garcia Vernet
 */
public class EditLevelMenu extends javax.swing.JPanel {

    
    ViewController viewController;
    String player;
    
    
    /**
     * Creates new form EditLevelMenu
     * @param viewController is the viewController of the application.
     */
    public EditLevelMenu(ViewController viewController) {
        initComponents();
        this.viewController = viewController;
        this.setSize(1280, 720);
        this.setVisible(false);
    }

    
    /**
     * Initializes the view. Creates a list with the names of the levels and 
     * shows it. Selecting a level with the mouse opens the editor for that level.
     * @param user is the username of the current user.
     */
    public void init(String user) {
        player = user;
        levelsArray = new ArrayList<Level>();

        DefaultListModel<String> model = new DefaultListModel<>();
        List<List<Level>> levels = this.viewController.getLevelsBySize();

        int numLevels = 0;
        for (int l = 0; l < levels.size(); l++) {
            final var levelGroup = levels.get(l);
            String levelSize = "[Size " + levelGroup.get(0).getSize() + "]";
            for (int i = 0; i < levelGroup.size(); i++) {
                final Level level = levelGroup.get(i);
                numLevels += 1;
                String levelName = levelSize.concat(" - " + numLevels + " (" + level.getCreator() + ")");
                model.addElement(levelName);
                levelsArray.add(level);
            }
        }
        
        levelsList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editLevelTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        levelsList = new javax.swing.JList<>();
        createNewLevelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        editLevelTitle.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        editLevelTitle.setText("EDIT LEVEL");

        levelsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        levelsList.setPreferredSize(new java.awt.Dimension(60, 187));
        levelsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelsListMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(levelsList);

        createNewLevelButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        createNewLevelButton.setText("Create new level");
        createNewLevelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewLevelButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollPane)
                            .addComponent(editLevelTitle)
                            .addComponent(createNewLevelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                .addContainerGap(544, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(editLevelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createNewLevelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creates a new game and opens the editor for that level.
     */
    private void createNewLevelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewLevelButtonActionPerformed
        try {
            ArrayList<Cell> cells = new ArrayList<>();
            cells.add(new Cell(1, 0));
            ArrayList<Partition> partitions = new ArrayList<>();
            partitions.add(new Partition(1, 1, Operations.NoOp));
            Board board = new Board(1, cells, partitions);
            Game game = new Game(-1, board);
            viewController.BoardView(true, player, game);
        } catch (Exception ex) {
            System.err.println("Error when editing new board: " + ex.getMessage());
        }
    }//GEN-LAST:event_createNewLevelButtonActionPerformed

    /**
     * Returns to the previous view.
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.viewController.popView();
    }//GEN-LAST:event_backButtonActionPerformed

    private void levelsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelsListMouseClicked
        try {
            int gameSelected = levelsArray.get(levelsList.getSelectedIndex()).getId();
            Game game = viewController.startNewGame(player, gameSelected);                                      
            viewController.BoardView(true, player, game);
        } catch (Exception ex) {
            System.err.println("Error when editing an existing level: " + ex.getMessage());
        }
    }//GEN-LAST:event_levelsListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createNewLevelButton;
    private javax.swing.JLabel editLevelTitle;
    private javax.swing.JList<String> levelsList;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Level> levelsArray;
}
